baseURL: 'https://rizalasrul.com/'
title: 'Rizal Asrul Pambudi'
paginate: 5
theme: 'PaperMod'
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: 'UA-178654136-1'
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'rizalasrul.com'
  description: 'Personal website/blog of Rizal Asrul Pambudi'
  keywords: ['Rizal', 'Asrul', 'Pambudi', 'Personal Website', 'CV', 'Blog']
  author: 'Rizal Asrul Pambudi'
  images: ['/opengraph.png']
  DateFormat: 'January 2, 2006'
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    favicon: '/me.jpeg'
    favicon16x16: '/me.jpeg'
    favicon32x32: '/me.jpeg'
    apple_touch_icon: '/me.jpeg'
    safari_pinned_tab: '/me.jpeg'
  label:
    text: 'Home'
  profileMode:
    enabled: true
    title: 'Rizal Asrul Pambudi'
    subtitle: 'Truth can only be found in one place, the code'
    imageUrl: '/me.jpeg'
    imageWidth: 120
    imageHeight: 120
    imageTitle: 'Rizal avatar'
    buttons:
      - name: 'Blog 📝'
        url: blog
      - name: 'TIL 💡'
        url: til
  socialIcons:
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/rizalasrul/'
    - name: 'instagram'
      url: 'https://instagram.com/rizalasrul'
    - name: 'github'
      url: 'https://github.com/rizalasrul'
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']
outputs:
  home:
    - HTML
    - RSS
    - JSON
